solana-block-scanner:
  image:
    repository: solana-indexer-solana-block-scanner
  blockchain: solana
  environments:
    APPLICATION_ENVIRONMENT: '{{ include "service.appEnv" $ }}'
    CONSUL_ROOT_PATH: '{{ include "service.appEnv" $ }}/protocol/{{ .Values.blockchain }}/block-scanner'
    SPRING_PROFILES_ACTIVE: '{{ .Values.blockchain }},consul,{{ include "service.appEnv" $ }},{{ .Values.blockchain }}-{{ include "service.appEnv" $ }}'
  nodeSelector:
    node.labels.rarible.job: true
  endpointMode: dnsrr
  resources:
    jvm:
      xmx_megabytes: 356
      max_direct_memory_megabytes: 32
  networks:
    common:
      - '{{ include "service.appEnv" $ }}-backend'

solana-indexer:
  image:
    repository: solana-indexer-solana-indexer
  blockchain: solana
  environments:
    APPLICATION_ENVIRONMENT: '{{ include "service.appEnv" $ }}'
    CONSUL_ROOT_PATH: '{{ include "service.appEnv" $ }}/protocol/{{ .Values.blockchain }}/nft'
    SPRING_PROFILES_ACTIVE: '{{ .Values.blockchain }},consul,{{ include "service.appEnv" $ }},{{ .Values.blockchain }}-{{ include "service.appEnv" $ }}'
  nodeSelector:
    node.labels.rarible.job: true
  endpointMode: dnsrr
  resources:
    jvm:
      xmx_megabytes: 512
      max_direct_memory_megabytes: 32
  livenessProbe:
    initialDelaySeconds: 180s
  networks:
    common:
      - '{{ include "service.appEnv" $ }}-backend'