spring:
  application.name: protocol-solana-indexer-api
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    default-property-inclusion: non_null
  main:
    banner-mode: log
    web-application-type: reactive

common:
  ipfs:
    ipfsPrivateGateway: "https://nftstorage.link"
    ipfsPublicGateway: "https://ipfs.io"
  metricRootPath: solana-nft-metrics
  featureFlags:
    skipTransfersWithUnknownMint: false

mongock:
  change-logs-scan-package:
    - com.rarible.blockchain.scanner.solana.migration

rarible:
  core:
    apm:
      agent:
        enabled: true
        server: http://apm-server.logging:8200
        packages: com.rarible.protocol.solana.nft.api
      web:
        filter:
          enabled: true
      annotation:
        enabled: true