application:
  project: protocol

server:
  shutdown: graceful
  port: 8080

spring:
  application.name: protocol-${scanner.blockchain}-block-scanner
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    default-property-inclusion: non_null
  aop:
    proxy-target-class: false
  main:
    banner-mode: log
    web-application-type: reactive

rarible:
  core:
    apm:
      agent:
        enabled: true
        server: http://elk_apm-server:8200
        packages: com.rarible.protocol.block.scanner
      annotation:
        enabled: true

blockchain:
  scanner:
    kafka:
      maxPollRecords: 100
    solana:
      rpcApiUrl: "https://api.mainnet-beta.solana.com"
      scan:
        event-consume:
          enabled: false
      retryPolicy:
        scan:
          reconnectDelay: 2s
          reconnectAttempts: 1
        client:
          delay: 2s
          attempts: 3
      job:
        reconciliation:
          enabled: false
          batchSize: 5
      monitoring:
        enabled: true
        rootPath: "blockchain.scanner"
        worker:
          pollingPeriod: 1m

mongock:
  change-logs-scan-package:
    - com.rarible.blockchain.scanner.solana.migration
