spring:
  data:
    mongodb:
      uri: mongodb://${mongodb.hosts}
      database: ${mongodb.database}

blockchain:
  scanner:
    kafka:
      broker-replica-set: ${kafka.hosts}

common:
  kafka-replica-set: ${kafka.hosts}
